### ISSUE TITLE
lib-rgbpanel: H3, did we ever get to two panels working?

### ISSUE THREAD

**Issue by hippyau** [vanvught/rpidmx512#221]
Hey Arjan,

I'd like to make a square, so two 2 x  64x32 panels vertically,  giving a 'round' clock face of 64x64.
Have you had 2 panels running, just by daisy chaining?   I recall was theorized? 

Looking to generate a TOD clock (or radar!) display, just ideas at the moment.

Hope you are well :)

Cheers,
 hip

**Comment by vanvught** [comment]
Hi Hip,

I have not yet 2 panels running. Or better saying; never tried, yet.

It should work fine with the limitation that we must lower the PWM with -> https://github.com/vanvught/rpidmx512/blob/development/lib-rgbpanel/include/rgbpanel.h#L32 in order to keep the FPS relatively high.

Groet, Arjan
