### ISSUE TITLE
RemoteConfigUI: Add support for LTC SMPTE Display WS28xx UDP messages

### ISSUE THREAD

**Issue by vanvught** [vanvught/rpidmx512#79]
http://www.orangepi-dmx.org/orange-pi-smpte-timecode-ltc-reader-converter/ws28xx-7-segment/run-time-udp-messages

cc @hippyau

**Comment by vanvught** [comment]
![Schermafbeelding 2019-11-09 om 20 44 56](https://user-images.githubusercontent.com/4319913/68534210-df213e00-0331-11ea-9c45-c4cc1c156eb7.png)

cc @hippyau

**Comment by vanvught** [comment]
[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/3827679/RemoteConfigUI.jar.zip)

cc @hippyau

**Comment by hippyau** [comment]
Hi Arjan!

 Thanks for this!  Unfortunately, it's not working because it seems like the UI is still sending to UDP port 21571 not the new port of 10258.   The device responds to echo command lines properly.

![image](https://user-images.githubusercontent.com/36442309/68538792-a8950300-03c5-11ea-9d17-5f263f0dba07.png)

Cheers, 
 hip

**Comment by vanvught** [comment]
Hi Hip,

That's a bummer. My lesson's learned; never work off-line again - do always a proper test ;-)

Greetings, Arjan


[RemoteConfigUI.jar.zip](https://github.com/vanvught/rpidmx512/files/3828183/RemoteConfigUI.jar.zip)

**Comment by hippyau** [comment]
Wow, thanks for the quick fix!  Now works beautifully.  :)

**Comment by hippyau** [comment]
Hi Arjan, 
   Thanks so much, this one works great!
Cheers, hip

**Comment by hippyau** [comment]
Thanks so much, is all good now!

**Comment by vanvught** [comment]
Available in staging branch -> https://github.com/vanvught/rpidmx512/commit/72d007d264d2e013714a70c6fc6166c3192019f7
