### ISSUE TITLE
Enhancement: Add support for rotary encoder

### ISSUE THREAD

**Issue by Vampir8** [vanvught/rpidmx512#88]
Hello
Can you add rotary encoder support for change port, universe, sACN / Art-net, IP?

**Comment by vanvught** [comment]
Hi, implementing support for a rotary encoder navigating through several menu's on the OLED display would involve a lot of coding. And also it would take a lot of time. Moreover, it would move away from my mission working on the core processes only; these processes are doing the job.

However, in order to support a flexible UI when the user is requesting for it, I have opened #66 
And also https://github.com/vanvught/opi-nextion
This gives you the freedom to create your own UI with your own specification.
